apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
        api: external
    spec:
      containers:
        - name: udagram-reverseproxy
          image: hakimks/udagram-reverseproxy:v1
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
      restartPolicy: Always
